title: Stackbit DIY Theme
baseURL: /
params:
  layout_type: boxed
  style: classic
  palette: green
  mode: light
  base_font: serif
  header:
    type: header
    title: DIY
    logo: /images/Nouvelle branche - 1000x1000.png
    logo_alt: Nouvelle Branche logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        label: Pourquoi?
        url: /features
        style: link
      - type: action
        label: La démarche
        url: /pricing
        style: link
      - type: action
        label: À propos de moi
        url: /about
        style: link
      - type: action
        label: Blogue
        url: /blog
        style: link
      - type: action
        label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - type: action
        label: Me contacter
        url: /contact
        style: link
      - type: action
        label: Mon infolettre
        url: /pricing
        style: primary
    has_anncmnt: true
    anncmnt_content: >
      Nouveau site web. [**Suivez mon parcours en vous abonnant à mon infolettre
      :)**](akiamarketing.ca)
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    type: footer
    logo: /images/Nouvelle branche - 1000x1000.png
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_title: À propos
    primary_nav_links:
      - type: action
        label: La démarche
        url: /about
        style: link
      - type: action
        label: Pourquoi?
        url: /style-guide
        style: link
      - label: À propos
        url: '#'
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        no_follow: false
        type: action
    has_secondary_nav: true
    secondary_nav_title: Blogue
    secondary_nav_links:
      - type: action
        label: News
        url: /blog/category/news
        style: link
      - type: action
        label: General
        url: /blog/category/general
        style: link
      - type: action
        label: Tutorials
        url: /blog/category/tutorials
        style: link
    has_tertiary_nav: true
    tertiary_nav_title: Légal
    tertiary_nav_links:
      - type: action
        label: Termes et conditions
        url: /terms-conditions
        style: link
      - type: action
        label: Politique de confidentialité
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - type: action
        label: Twitter
        url: 'https://twitter.com/'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - type: action
        label: GitHub
        url: 'https://github.com/'
        style: link
        has_icon: true
        icon: github
        icon_position: center
        new_window: true
      - type: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
      - type: action
        label: YouTube
        url: 'https://www.youtube.com/'
        style: link
        has_icon: true
        icon: youtube
        icon_position: center
        new_window: true
      - type: action
        label: Vimeo
        url: 'https://vimeo.com/'
        style: link
        has_icon: true
        icon: vimeo
        icon_position: center
        new_window: true
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=diy&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
  domain: 'https://blog-environnement-6853c.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
